### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by ljymrl** [nsidn98/InforMARL#11]
Hello, thank you so much for open-sourcing such a great program, I've learned a lot in it and really appreciate it! But I encountered the following error in running the code, please answer, thank you!
Traceback (most recent call last):
  File "/home/ljy/.conda/envs/infornmarl/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/ljy/.conda/envs/infornmarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ljy/InforNMARL/onpolicy/envs/env_wrappers.py", line 941, in graphworker
    ob, ag_id, node_ob, adj, reward, done, info = env.step(data)
  File "/home/ljy/InforNMARL/multiagent/environment.py", line 703, in step
    self.update_graph(self.world)
  File "/home/ljy/InforNMARL/multiagent/custom_scenarios/navigation_graph.py", line 400, in update_graph
    sparse_connect = sparse.csr_matrix(connect)
  File "/home/ljy/.conda/envs/infornmarl/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 85, in __init__
    self._coo_container(arg1, dtype=dtype)
  File "/home/ljy/.conda/envs/infornmarl/lib/python3.8/site-packages/scipy/sparse/_coo.py", line 130, in __init__
    if isinstance(arg1, tuple):
TypeError: __init__() takes 1 positional argument but 3 were given

**Comment by ljymrl** [comment]
This is a problem that occurs during the run, at first there are no errors reported

**Comment by nsidn98** [comment]
Hi @ljymrl! Glad that you found the code useful! Could you please let me know what version of scipy you are using? I think the issue is arising from there. I used `scipy==1.10.1` for this.

**Comment by ljymrl** [comment]
Thank you!
