### ISSUE TITLE
RuntimeError: Function ViewBackward returned an invalid gradient at index 0 - expected device cpu:0 but got cpu

### ISSUE THREAD

**Issue by s1101818** [nsidn98/InforMARL#27]
im trying to run the project on other machine with cpu then this shows up i change config file
```
parser.add_argument(
        "--cuda",
        action="store_false",
        default=Fales,
        help="by default True, will use GPU to train; " "or else will use CPU;",
    )
```
still not working
how can i fix it
```
Average episode rewards is -153.109 	Total timesteps: 195200 	 Percentage complete 3.904
Traceback (most recent call last):
  File "onpolicy/scripts/train_mpe.py", line 315, in <module>
    main(sys.argv[1:])
  File "onpolicy/scripts/train_mpe.py", line 300, in main
    runner.run()
  File "/home/lab688/work/pythonproject/kinformarl/InforMARL-main/onpolicy/runner/shared/graph_mpe_runner.py", line 76, in run
    train_infos = self.train()
  File "/home/lab688/work/pythonproject/kinformarl/InforMARL-main/onpolicy/runner/shared/base_runner.py", line 168, in train
    train_infos = self.trainer.train(self.buffer)
  File "/home/lab688/work/pythonproject/kinformarl/InforMARL-main/onpolicy/algorithms/graph_mappo.py", line 333, in train
    ) = self.ppo_update(sample, update_actor)
  File "/home/lab688/work/pythonproject/kinformarl/InforMARL-main/onpolicy/algorithms/graph_mappo.py", line 246, in ppo_update
    critic_loss.backward()
  File "/home/lab688/work/anaconda3/envs/informarl37/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lab688/work/anaconda3/envs/informarl37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function ViewBackward returned an invalid gradient at index 0 - expected device cpu:0 but got cpu
```

**Comment by nsidn98** [comment]
Could you try after fixing the typo "Fales" to "False"?

**Comment by s1101818** [comment]
yes i did and the result are same

**Comment by nsidn98** [comment]
Gotcha! Let me take a look at this. Can you maybe share the command you are running to execute the code?
Example: `python blah.py`

**Comment by s1101818** [comment]
here is commend i use :
```
(my_conda_env)>bash informarl.sh
```
on terminal

**Comment by nsidn98** [comment]
I think `informarl.sh` is a deprecated script. Could you try running the following command instead:
```
python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \
--project_name "informarl" \
--env_name "GraphMPE" \
--algorithm_name "rmappo" \
--seed 0 \
--experiment_name "informarl" \
--scenario_name "navigation_graph" \
--num_agents 3 \
--collision_rew 5 \
--n_training_threads 1 --n_rollout_threads 128 \
--num_mini_batch 1 \
--episode_length 25 \
--num_env_steps 2000000 \
--ppo_epoch 10 --use_ReLU --gain 0.01 --lr 7e-4 --critic_lr 7e-4 \
--user_name "marl" \
--use_cent_obs "False" \
--graph_feat_type "relative" \
--auto_mini_batch_size --target_mini_batch_size 128python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \
--project_name "informarl" \
--env_name "GraphMPE" \
--algorithm_name "rmappo" \
--seed 0 \
--experiment_name "informarl" \
--scenario_name "navigation_graph" \
--num_agents 3 \
--collision_rew 5 \
--n_training_threads 1 --n_rollout_threads 128 \
--num_mini_batch 1 \
--episode_length 25 \
--num_env_steps 2000000 \
--ppo_epoch 10 --use_ReLU --gain 0.01 --lr 7e-4 --critic_lr 7e-4 \
--user_name "marl" \
--use_cent_obs "False" \
--graph_feat_type "relative" \
--auto_mini_batch_size --target_mini_batch_size 128
```

**Comment by s1101818** [comment]
@nsidn98 
i use commend :bash yourcommend.sh
and its still shows 
```
RuntimeError: Function ViewBackward returned an invalid gradient at index 0 - expected device cpu:0 but got cpu
```
and i want to ask is there any way that i can run this moudel on higher versions gpu like 3060?? it seems not match with torch version??

**Comment by hsvgbkhgbv** [comment]
This may be due to that you created some variables that are fortgotten to be moved to the GPU, during training.

**Comment by s1101818** [comment]
@hsvgbkhgbv
im not sure about that, becauce the training will stop at different points in time, I'm still checking what is causing this issue, maybe there's other setting that i didn't check.....IDK :(

**Comment by hsvgbkhgbv** [comment]
Can you leave your WeChat ID? Maybe we can have a chat.

**Comment by s1101818** [comment]
@nsidn98 HI sorry to bother you again
do you use tensorboard to generate the graph diagram of the architecture in your code?
I would like to use this to understand, or where can I add the relevant code to generate the architecture diagram?

**Comment by s1101818** [comment]
ummm are you there?? sir??

**Comment by s1101818** [comment]
Hey...are you still here, sir?
@nsidn98 

@hsvgbkhgbv 
i already fix it thx

**Comment by nsidn98** [comment]
@s1101818 apologies for the late reply! I will go through this after next week (travelling to NeurIPS) and try to find a fix. We do not use tensorboard but we use wandb. You can visualise the model like [this](https://community.wandb.ai/t/how-to-visualize-model-graph-in-weights-and-biases/2547)

**Comment by s1101818** [comment]
Thank you!!
I don't know much about add_graph() but I will also try wand, can wandb display a graph of a model?(but i want to ask if you guys use wandb then whats the tensorboardX for??)
Anyway, I'll come back here again if I have any other questions.
I appreciate that you made such an interesting model.

**Comment by nsidn98** [comment]
I am glad that you found the project interesting! I will get back soon with a fix for this. 

Yes, wandb allows you to visualise the graph. You can also use tensorboard instead of wandb if you are more comfortable with using it.

**Comment by s1101818** [comment]
@nsidn98 
i want to decrease the train step let wandb out put the model graph at windows what number should i change ??
i try set the num_env_steps from 200000 to 200
```
python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \
--project_name "informarl" \
--env_name "GraphMPE" \
--algorithm_name "rmappo" \
--seed 0 \
--experiment_name "informarl" \
--scenario_name "navigation_graph" \
--num_agents 3 \
--collision_rew 5 \
--n_training_threads 1 --n_rollout_threads 128 \
--num_mini_batch 1 \
--episode_length 25 \
--num_env_steps 200 \
--ppo_epoch 10 --use_ReLU --gain 0.01 --lr 7e-4 --critic_lr 7e-4 \
--user_name "<INSERT_YOUR_WANDB_NAME>" \
--use_cent_obs "False" \
--graph_feat_type "relative" \
--auto_mini_batch_size --target_mini_batch_size 128
~                                                     
```
im not shore is this work or not

```
Traceback (most recent call last):
  File "onpolicy/scripts/train_mpe.py", line 315, in <module>
    main(sys.argv[1:])
  File "onpolicy/scripts/train_mpe.py", line 289, in main
    runner = Runner(config)
  File "/home/lab688/work/pythonproject/K_Informarl_retry/InforMARL-main/onpolicy/runner/shared/graph_mpe_runner.py", line 24, in __init__
    super(GMPERunner, self).__init__(config)
  File "/home/lab688/work/pythonproject/K_Informarl_retry/InforMARL-main/onpolicy/runner/shared/base_runner.py", line 66, in __init__
    self.save_dir = str(wandb.run.dir)
AttributeError: 'NoneType' object has no attribute 'dir'
new_test20.sh: line 2: --project_name: command not found
new_test20.sh: line 3: --env_name: command not found
new_test20.sh: line 4: --algorithm_name: command not found
new_test20.sh: line 5: --seed: command not found
new_test20.sh: line 6: --experiment_name: command not found
new_test20.sh: line 7: --scenario_name: command not found
new_test20.sh: line 8: --num_agents: command not found
new_test20.sh: line 9: --collision_rew: command not found
new_test20.sh: line 10: --n_training_threads: command not found
new_test20.sh: line 11: --num_mini_batch: command not found
new_test20.sh: line 12: --episode_length: command not found
new_test20.sh: line 13: --num_env_steps: command not found
new_test20.sh: line 14: --ppo_epoch: command not found
new_test20.sh: line 15: --user_name: command not found
new_test20.sh: line 16: --use_cent_obs: command not found
new_test20.sh: line 17: --graph_feat_type: command not found
new_test20.sh: line 18: --auto_mini_batch_size: command not found

```
and this error shows up when i turn on the wandb

how do i do?

**Comment by Poorya1988** [comment]
Hi, is it possible to run some inference? 
I think you just wrote the prompt of training and not the inference.
Thanks

**Comment by Poorya1988** [comment]
> Hi, is it possible to run some inference? I think you just wrote the prompt of training and not the inference. Thanks

Hi, thanks to @nsidn98, I got the test prompt, I will put it below, 

Example usage: python onpolicy/scripts/eval_mpe.py  --model_dir='YOUR_PATH_TO_SAVED_WEIGHTS_FOLDER' --render_episodes=1 --world_size=1 --num_agents=<NUM_AGENTS> --num_obstacles=<NUM_OBSTACLES> --seed=0 --num_landmarks=<NUM_AGENTS> --episode_length=25 --use_dones=True

Keep in mind, "--model_dir" refers to the "critic.pt" and "actor.pt" which are in the "\onpolicy\results\GraphMPE\navigation_graph\rmappo\informarl\wandb\run\files" path.

Another thing to say is the output which looks like the image I will attach,
![result](https://github.com/user-attachments/assets/149fc839-548f-49a9-ad69-8ed7f27a8c5a)

based on the image provided,
the model was executed for 1 episode, got a reward of 268.5, the episode was completed in ~0.27*25 steps (25 is the horizon of the episode) and 2 collisions happened in the episode

**Comment by nsidn98** [comment]
@s1101818 How are you executing the script? Can you show me the exact command you are running? It might be an issue with bash/zsh shells you are using.
