### ISSUE TITLE
The parameter logits has invalid values

### ISSUE THREAD

**Issue by hsvgbkhgbv** [nsidn98/InforMARL#28]
Thanks for sharing such an interesting repo. However, when I run the code the following bugs appear:

Traceback (most recent call last):
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/scripts/train_mpe.py", line 315, in <module>
    main(sys.argv[1:])
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/scripts/train_mpe.py", line 300, in main
    runner.run()
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/runner/shared/graph_mpe_runner.py", line 76, in run
    train_infos = self.train()
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/runner/shared/base_runner.py", line 168, in train
    train_infos = self.trainer.train(self.buffer)
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/graph_mappo.py", line 298, in train
    actor_grad_norm, imp_weights, actor_bt, critic_bt = self.ppo_update(sample, update_actor)
  File "/PUHTI_TYKKY_4v1SrvP/miniconda/envs/env1/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 139, in decorate_autocast
    return func(*args, **kwargs)
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/graph_mappo.py", line 152, in ppo_update
    values, action_log_probs, dist_entropy = self.policy.evaluate_actions(
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/graph_MAPPOPolicy.py", line 255, in evaluate_actions
    action_log_probs, dist_entropy = self.actor.evaluate_actions(
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/graph_actor_critic.py", line 260, in evaluate_actions
    action_log_probs, dist_entropy = self.act.evaluate_actions(
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/utils/act.py", line 215, in evaluate_actions
    action_logits = self.action_out(x, available_actions)
  File "/PUHTI_TYKKY_4v1SrvP/miniconda/envs/env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/projappl/project_2008459/InforMARL-dev/onpolicy/algorithms/utils/distributions.py", line 94, in forward
    return FixedCategorical(logits=x)
  File "/PUHTI_TYKKY_4v1SrvP/miniconda/envs/env1/lib/python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/PUHTI_TYKKY_4v1SrvP/miniconda/envs/env1/lib/python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter logits has invalid values

Could you please take a look?

**Comment by nsidn98** [comment]
Hi @hsvgbkhgbv! Could you please let me know the command you are running to execute, the OS and whether you are running it on a GPU or not?

**Comment by hsvgbkhgbv** [comment]
My OS info is as follows:

```
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
```

I run it on a slurm server with 1 V100 GPU with CPU cores=40, the same as yours.

The command I used is the slurm file `informarl.sh`.

**Comment by nsidn98** [comment]
I believe `informarl.sh` is a deprecated script. Could you maybe try running this instead:
```
python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \
--project_name "informarl" \
--env_name "GraphMPE" \
--algorithm_name "rmappo" \
--seed 0 \
--experiment_name "informarl" \
--scenario_name "navigation_graph" \
--num_agents 3 \
--collision_rew 5 \
--n_training_threads 1 --n_rollout_threads 128 \
--num_mini_batch 1 \
--episode_length 25 \
--num_env_steps 2000000 \
--ppo_epoch 10 --use_ReLU --gain 0.01 --lr 7e-4 --critic_lr 7e-4 \
--user_name "<your_WANDB_username>" \
--use_cent_obs "False" \
--graph_feat_type "relative" \
--auto_mini_batch_size --target_mini_batch_size 128
```

**Comment by hsvgbkhgbv** [comment]
I figured it out. Thanks for your help.

**Comment by nsidn98** [comment]
@hsvgbkhgbv did it work for you? If yes, could you close this issue?

Thanks!

**Comment by hsvgbkhgbv** [comment]
Following the installation instruction in https://github.com/Jaroan/Fair-MARL can address this issue.
