### ISSUE TITLE
Installation details

### ISSUE THREAD

**Issue by SJTUGuofei** [nsidn98/InforMARL#7]
Which Python version used?
Could you please detail the installation dependencies and procedures? 
Thx.

**Comment by nsidn98** [comment]
Hi @SJTUGuofei! I used Python 3.10 and the library versions are given in the README. You can also refer to #1. Let me know if none of these work for you.

**Comment by nsidn98** [comment]
@SJTUGuofei were you able to install the necessary libraries? Let me know if you need help:)

**Comment by SJTUGuofei** [comment]
When I use pip install then return the follow issues:
pip install requirement.txt 
ERROR: Could not find a version that satisfies the requirement requirement.txt (from versions: none)
ERROR: No matching distribution found for requirement.txt

and I use python 3.10

Then I use pip install every dependencies,
pip install numpy==1.19.4   then returns
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

pip install protobuff==3.20.0  returns
ERROR: Could not find a version that satisfies the requirement protobuff==3.20.0 (from versions: none)
ERROR: No matching distribution found for protobuff==3.20.0

or even 
pip install protobuff
ERROR: Could not find a version that satisfies the requirement protobuff (from versions: none)
ERROR: No matching distribution found for protobuff

So could you help me, thank you so much.

**Comment by nsidn98** [comment]
I think the command to install from a requirement.txt file is `pip install -r requirement.txt`

I think the [protobuf error](https://github.com/protocolbuffers/protobuf/issues/10070) shows up when using python<3.6. But since you are using python 3.10, I am not sure what is the exact issue here.

Could you please let me know what OS you are using and if you are using Conda?

**Comment by SJTUGuofei** [comment]
I use Ubuntu22.04, Anaconda3 and python3.8, I successfully install the dependencies one by one, the detail dependencies are ,
Package                Version
---------------------- -----------
absl-py                2.1.0
cachetools             4.2.4
certifi                2024.2.2
cffi                   1.16.0
chardet                3.0.4
charset-normalizer     3.3.2
click                  8.1.7
configparser           6.0.1
docker-pycreds         0.4.0
future                 0.18.3
gitdb                  4.0.11
GitPython              3.1.42
google-auth            1.35.0
google-auth-oauthlib   0.4.6
grpcio                 1.62.1
gym                    0.10.5
idna                   2.8
importlib_metadata     7.0.2
Jinja2                 3.1.3
joblib                 1.3.2
Markdown               3.5.2
MarkupSafe             2.1.5
mkl-fft                1.3.1
mkl-random             1.2.2
mkl-service            2.4.0
numpy                  1.24.3
oauthlib               3.2.2
pandas                 2.0.3
pathtools              0.1.2
pillow                 10.2.0
pip                    23.3.1
promise                2.3
protobuf               3.20.1
psutil                 5.9.8
pyasn1                 0.5.1
pyasn1-modules         0.3.0
pycparser              2.21
pyglet                 2.0.14
PyOpenGL               3.1.5
pyparsing              3.1.2
PyQt5                  5.15.10
PyQt5-Qt5              5.15.2
PyQt5-sip              12.13.0
python-dateutil        2.9.0.post0
pytz                   2024.1
PyYAML                 6.0.1
requests               2.22.0
requests-oauthlib      1.4.0
rsa                    4.9
scikit-learn           1.3.2
scipy                  1.10.1
sentry-sdk             1.41.0
setproctitle           1.3.3
setuptools             68.2.2
shortuuid              1.0.13
six                    1.16.0
smmap                  5.0.1
subprocess32           3.5.4
tensorboard            2.4.0
tensorboard-plugin-wit 1.8.1
tensorboardX           2.1
threadpoolctl          3.3.0
torch                  1.8.1
torch-cluster          1.6.3
torch-geometric        2.0.4
torch-scatter          2.1.0
torch-sparse           0.6.18
torch-spline-conv      1.2.2
torchvision            0.9.1
tqdm                   4.44.1
typing                 3.6.4
typing-extensions      3.7.4.3
tzdata                 2024.1
urllib3                1.25.11
wandb                  0.10.31
Werkzeug               3.0.1
wheel                  0.41.2
zipp                   3.18.0


When I tun the test example,  python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \...
It retuns,
Traceback (most recent call last):
  File "onpolicy/scripts/train_mpe.py", line 315, in <module>
    main(sys.argv[1:])
  File "onpolicy/scripts/train_mpe.py", line 208, in main
    with open(os.path.expanduser("~") + "/keys.json") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/guofei/keys.json'

**Comment by nsidn98** [comment]
Hi @SJTUGuofei, glad that you were able to install all the necessary libraries! 

To fix the error above, you will need to create a `keys.json` file in your home folder.
The json file should have the following content:
```json
{"my_wandb_api_key": "put_your_wandb_api_key_here"}
```
You can find your [wandb API key](https://wandb.ai/authorize) after you make an account.

**Comment by nsidn98** [comment]
Closing this due to inactivity. Please reopen if the issue still persists. Thanks!

**Comment by nsidn98** [comment]
Closing this due to inactivity. Please reopen if the issue still persists. Thanks!
